""""""""""""""""""""""""""""""""""""""""""""""""""
" General settings
""""""""""""""""""""""""""""""""""""""""""""""""""

let mapleader=" "

set history=500

syntax enable
filetype plugin on
filetype indent on

" auto read when a file is changed from the outside
set autoread
autocmd FocusGained,BufEnter * silent! checktime

set autowrite

" number of lines to the cursor when moving vertically using j/k
set scrolloff=3

set number relativenumber

set wildmenu
set wildmode=longest:list,full
set wildignore+=*.o,*~,*.pyc,*/.git/*,*/.DS_Store
set wildignorecase

set ruler

" indicate mode with a cursor shape
set noshowmode
let &t_SI.="\e[5 q" " insert mode
let &t_EI.="\e[2 q" " normal mode
autocmd InsertEnter * set ttimeout ttimeoutlen=1
autocmd InsertLeave * set nottimeout ttimeoutlen=-1

set hidden

set backspace=eol,start,indent

set whichwrap+=<,>,h,l

set ignorecase
set smartcase
set incsearch
set hlsearch

" show partial commands as they are typed
set showcmd

" show highlight of matching brackets
set showmatch

" how many tenths of a second to blink when matching brackets
set matchtime=2

set novisualbell

if has("gui_running")
    set macligatures
    set guifont=Fira\ Code:h15
    "set guifont=Monaco:h15
endif

" how long to wait for further keys
set timeoutlen=1000

" encoding displayed
set encoding=utf8
" encoding written
set fileencoding=utf-8

" always show the status line
set laststatus=2

set nobackup
set nowritebackup
set noswapfile

set wrap

set nojoinspaces

" save undo trees in files
set undofile
set undodir=~/.vim/undo
set undolevels=10000

set path+=**

set regexpengine=0

" break lines at word boundaries
set linebreak

set splitbelow
set splitright

highlight VertSplit cterm=NONE guifg=NONE

" automatically generate tags file for given filetypes
if !empty(expand(glob("tags")))
    autocmd BufWritePost *.py,*.R,*.Rmd,*.awk silent! !ctags -o newtags -R .; mv newtags tags &
end

" in command mode, use normal ignorecase, not smartcase
augroup dynamic_smartcase
    autocmd!
    autocmd CmdLineEnter : set nosmartcase
    autocmd CmdLineLeave : set smartcase
augroup END

augroup terminal_behavior
    autocmd!
    " no line numbers in the terminal ever
    autocmd TerminalOpen * setlocal nonumber norelativenumber
augroup END

" taken from :help last-position-jump
augroup RestoreCursor
  autocmd!
  autocmd BufReadPost *
    \ let line = line("'\"")
    \ | if line >= 1 && line <= line("$") && &filetype !~# 'commit'
    \      && index(['xxd', 'gitrebase'], &filetype) == -1
    \      && !&diff
    \ |   execute "normal! g`\""
    \ | endif
augroup END

" use spaces instead of tabs
set expandtab

" pressing TAB respects context
set smarttab

" one TAB is four characters wide for everything
set shiftwidth=4
set tabstop=4
set softtabstop=4
" ... except for these R-specific settings:
autocmd FileType r :setlocal sw=2 ts=2 sts=2
let g:r_indent_align_args = 0
" ... and these Python-specific settings:
let g:pyindent_open_paren = 'shiftwidth()'

set autoindent

set nomodeline

" unlist terminal buffers (will be ignored by :ls and :bn / :bp)
autocmd TerminalOpen * if bufwinnr('') > 0 | setlocal nobuflisted | endif

""""""""""""""""""""""""""""""""""""""""""""""""""
" Custom commands and shortcuts
""""""""""""""""""""""""""""""""""""""""""""""""""

nnoremap <silent> <leader>p :call ToggleBreakpoint()<cr>
nnoremap <silent> <leader>P :call ClearBreakpoints()<cr>

command! W execute 'w !sudo tee % > /dev/null' <bar> edit!

nnoremap <leader>n :set number! relativenumber!<cr>
nnoremap <leader>N :set relativenumber!<cr>

nnoremap <leader>h :set hlsearch!<cr>

" searche for the current visual selection forward or backward
vnoremap <silent> * :<C-u>call SelectionAction('')<cr>/<C-R>=@/<cr><cr>
vnoremap <silent> # :<C-u>call SelectionAction('')<cr>?<C-R>=@/<cr><cr>

" vimgrep for visual selection
vnoremap <silent> <leader>g :call SelectionAction('vimgrep')<CR>
" replace visual selection
vnoremap <silent> <leader>r :call SelectionAction('replace')<CR>

nnoremap <leader>q :botright copen<cr>
nnoremap <leader>Q :clist<cr>
nnoremap ]q :cnext<cr>
nnoremap [q :cprevious<cr>

nnoremap <leader>w :set wrap!<cr>

" find file in the root of the current project (if any)
nnoremap <leader>ff :edit <c-r>=FindRootDirectory()<cr>/**/*

nnoremap <leader>E :split $MYVIMRC<cr>
nnoremap <leader>S :source $MYVIMRC<cr>

" search for a given pattern only within the current screen view
nnoremap <silent> \ :call ScreenLocalSearch()<CR>

""""""""""""""""""""""""""""""""""""""""""""""""""
" Windows, buffers, tabs
""""""""""""""""""""""""""""""""""""""""""""""""""

" quick jump to a buffer
nnoremap <leader>l :ls<cr>:b<space>
nnoremap <leader>V :ls<cr>:sb<space>
nnoremap <leader>H :ls<cr>:vert sb<space>

" close the current buffer
nnoremap <leader>bx :bnext<cr>:bd#<cr>

" moving between buffers
nnoremap <leader><tab> :b#<cr>

" managing tabs
nnoremap <leader>te :tabedit<space>
nnoremap <leader>tc :tabnew<cr>
nnoremap <leader>tx :tabclose<cr>

" moving between tabs
nnoremap ]t :tabnext<cr>
nnoremap [t :tabprevious<cr>

" toggle between the current and the last accessed tab
let g:lasttab = 1
nnoremap <leader><bs> :exe "tabn ".g:lasttab<cr>
autocmd TabLeave * let g:lasttab = tabpagenr()

" if a buffer is already open in another window/tab, switch to it
set switchbuf=useopen,usetab,newtab
" always show tabline
set showtabline=1

" poor vim/tmux REPL shortcuts
nnoremap <silent> <leader><cr> :call SendToTmux('normal')<CR>
xnoremap <silent> <leader><cr> :<C-u>call SendToTmux('visual')<CR>

""""""""""""""""""""""""""""""""""""""""""""""""""
" Helper functions
""""""""""""""""""""""""""""""""""""""""""""""""""

" Feed a given string to the command line
function! CmdLine(str)
    call feedkeys(":" . a:str)
endfunction

" Select visually the word under cursor
function! SelectionAction(action) range
    let l:saved_reg = @"
    execute "normal! vgvy"

    let l:pattern = escape(@", "\\/.*'$^~[]")
    let l:pattern = substitute(l:pattern, "\n$", "", "")

    if a:action == 'vimgrep'
        call CmdLine("vimgrep '" . l:pattern . "' " )
    elseif a:action == 'replace'
        call CmdLine("%s" . '/'. l:pattern . '/')
    endif

    let @/ = l:pattern
    let @" = l:saved_reg
endfunction

" Find root of the current "project" (if any) based on the current open file
function! FindRootDirectory()
    let root = systemlist("git rev-parse --show-toplevel")[0]
    if v:shell_error
        return ""
    else
        return root
    endif
endfunction

let g:breakpoint_marker = " ##### breakpoint #####"

" Toggle `breakpoint()` (Python) or `browser()` (R) function call
function! ToggleBreakpoint()
    let l:line=getline('.')

    " does the current line already have a breakpoint?
    let l:has_breakpoint = match(l:line, g:breakpoint_marker)

    " if not, add a breakpoint matching the current buffer's language
    if has_breakpoint == -1
        if &filetype ==# 'python'
            execute "normal! obreakpoint()" .. g:breakpoint_marker .. "\<esc>^"
            write
        elseif &filetype ==# 'r'
            execute "normal! obrowser()" .. g:breakpoint_marker .. "\<esc>^"
            write
        else
            echo "Not applicable for this filetype!"
        endif
    else
        " if yes, delete the breakpoint
        normal! 0ddk^
    endif
endfunction

" Remove all `breakpoint()` (Python) or `browser()` (R) function calls
function! ClearBreakpoints()
    " create a breakpoint marker matching the current buffer's language
    if &filetype ==# 'python'
        let l:marker = "breakpoint\(\)" .. g:breakpoint_marker
    elseif &filetype ==# 'r'
        let l:marker = "browser\(\)" .. g:breakpoint_marker
    endif

    " delete all such markers (and avoid spamming the register)
    if l:marker != ""
        execute "g/^.*" .. l:marker .. ".*$/d _"
        write
    else
        echo "Not applicable for this filetype!"
    endif
endfunction

" Search for a given text only within the current window
function! ScreenLocalSearch()
    let l:prev_scrolloff = &scrolloff

    " select the entire screen top to bottom
    set scrolloff=0
    normal! VHoL
    execute "normal! \<Esc>``\<C-y>"

    let &scrolloff = l:prev_scrolloff

    " open the search prompt pre-filled with the visual bounds atom
    call feedkeys('/\%V', 'n')
endfunction

" Send either a current line (normal mode), a selection of text (visual mode),
" or a selected block (visual mode) to the {last} tmux pane (assumed to be
" running a REPL process of some kind)
function! SendToTmux(type)
  " save unnamed register state
  let l:saved_reg = getreg('"')
  let l:saved_type = getregtype('"')

  " remember visual mode type before yanking
  let l:vmode = visualmode()
  let l:start_line = line('.')

  if a:type ==# 'visual'
    " in visual mode, yank the exact visual selection
    normal! gv"yy
    let l:target_line = line("'>")
  else
    " in normal mode: yank the current line
    normal! "yyy
    let l:target_line = l:start_line
  endif

  " send text to tmux buffer and paste
  call system('tmux load-buffer -', @")
  call system('tmux paste-buffer -t {last}')
  call system('tmux send-keys -t {last} Enter')

  " restore unnamed register
  call setreg('"', l:saved_reg, l:saved_type)

  " advance cursor if needed
  if a:type ==# 'normal' || l:vmode ==# 'V'
    call cursor(l:target_line + 1, 1)
    if getline('.') =~# '^\s*$'
      call search('^\s*\S', 'W')
    endif
  endif
endfunction
